# Generated by Django 3.2.6 on 2021-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_lock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('preview', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
    ]
